export const mockUsers = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john.doe@example.com',
    sex: 'male' as const,
    phone: '+254712345678',
    nationalId: '12345678',
    county: 'nairobi' as const,
    position: 'Manager',
    department: 'IT',
    valid: true,
    _count: { Delegates: 3, FormSubmissions: 5 },
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    sex: 'female' as const,
    phone: '+254723456789',
    nationalId: '23456789',
    county: 'machakos' as const,
    position: 'Supervisor',
    department: 'HR',
    valid: false,
    _count: { Delegates: 1, FormSubmissions: 2 },
  },
  {
    id: 3,
    name: 'Peter Kamau',
    email: 'peter.kamau@example.com',
    sex: 'male' as const,
    phone: '+254734567890',
    nationalId: '34567890',
    county: 'embu' as const,
    position: 'Coordinator',
    department: 'Finance',
    valid: true,
    _count: { Delegates: 2, FormSubmissions: 8 },
  },
  {
    id: 4,
    name: 'Mary Wanjiku',
    email: 'mary.wanjiku@example.com',
    sex: 'female' as const,
    phone: '+254745678901',
    nationalId: '45678901',
    county: 'muranga' as const,
    position: 'Assistant',
    department: 'Operations',
    valid: true,
    _count: { Delegates: 0, FormSubmissions: 1 },
  },
  {
    id: 5,
    name: 'David Ochieng',
    email: 'david.ochieng@example.com',
    sex: 'male' as const,
    phone: '+254756789012',
    nationalId: '56789012',
    county: 'homabay' as const,
    position: 'Officer',
    department: 'Marketing',
    valid: false,
    _count: { Delegates: 1, FormSubmissions: 3 },
  },
];

export const mockForms = [
  {
    id: 'form-001-uuid',
    delegateId: 1,
    delegate: {
      name: 'Alice Muthoni',
      email: 'alice.muthoni@example.com',
      county: 'nairobi' as const,
    },
    User: {
      name: 'John Doe',
      email: 'john.doe@example.com',
    },
    Q_1_1: 'Yes',
    Q_1_2: 'Completed',
    Q_2_1: 'Approved',
    Q_2_2: 'No issues',
  },
  {
    id: 'form-002-uuid',
    delegateId: 2,
    delegate: {
      name: 'Robert Kiprotich',
      email: 'robert.kiprotich@example.com',
      county: 'machakos' as const,
    },
    User: {
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
    },
    Q_1_1: 'No',
    Q_1_2: 'Pending',
    Q_2_1: 'Under Review',
    Q_2_2: 'Needs clarification',
  },
  {
    id: 'form-003-uuid',
    delegateId: 3,
    delegate: {
      name: 'Grace Nyambura',
      email: 'grace.nyambura@example.com',
      county: 'embu' as const,
    },
    User: {
      name: 'Peter Kamau',
      email: 'peter.kamau@example.com',
    },
    Q_1_1: 'Yes',
    Q_1_2: 'Completed',
    Q_2_1: 'Approved',
    Q_2_2: 'All good',
  },
  {
    id: 'form-004-uuid',
    delegateId: 4,
    delegate: {
      name: 'Samuel Wekesa',
      email: 'samuel.wekesa@example.com',
      county: 'tharakanithi' as const,
    },
    User: null,
    Q_1_1: 'Yes',
    Q_1_2: 'In Progress',
    Q_2_1: 'Pending',
    Q_2_2: null,
  },
  {
    id: 'form-005-uuid',
    delegateId: 5,
    delegate: {
      name: 'Catherine Akinyi',
      email: 'catherine.akinyi@example.com',
      county: 'homabay' as const,
    },
    User: {
      name: 'David Ochieng',
      email: 'david.ochieng@example.com',
    },
    Q_1_1: 'No',
    Q_1_2: 'Not Started',
    Q_2_1: 'Rejected',
    Q_2_2: 'Missing documents',
  },
];

// Mock stats
export const mockStats = {
  totalUsers: mockUsers.length,
  totalForms: mockForms.length,
  validUsers: mockUsers.filter((user) => user.valid).length,
  totalDelegates: 12,
};
